### ISSUE TITLE
Metadata frames and frame metadata

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket#13] opened 2015-08-06 06:35 UTC
At this point we have two concepts defined in the Protocol:

- _Metadata Push frame_:  This frame can be sent from either requestor or responder and are co-related to the following data frame.
- _Frame metadata_: Each frame also can contain metadata.

I may be missing usecases but I think these two are redundant. 

As it is mentioned in the spec, If the streams are ordered, a preceding metadata frame can define metadata for the next data frame. OTOH, the metadata in a frame can be used to just define metadata without any data (the metadata push frame semantics). 

It appears to me that we can do away with one of these concepts.

**Comment by tmontgomery** [comment] 2015-08-06 15:48
We want to have metadata attached to three different things.

1. Connection. This is provided by METADATA_PUSH.
1. Stream. This is provided by METADATA_PUSH.
1. Request, onComplete, onError, onNext, etc.. This is provided by Metadata header.

The problem is that by only allowing Metadata header, we have to add a special frame type for the first two to be provided. With only METADATA_PUSH, we don't have a means to provide onNext attachment of metadata aside from ordering. And with ordering, we also  have issues with how to provide metadata for Requests and other frame types.

**Comment by benjchristensen** [comment] 2015-08-12 23:45
Additionally, we are accounting for implementation complexity as well, not just over-the-wire behavior. If a client has to be capable of buffering and interpreting METADATA+NEXT frame reception, that increases complexity and cost as it must store, then allocate a new combined tuple/object for use by the application. 

For metadata that is specifically associated with a message, it is far clearer, and easier to process, if the metadata is part of the frame. Then a client can receive each frame without buffering or logic, and directly access the metadata related to the message if it has any.

**Comment by benjchristensen** [comment] 2015-08-12 23:48
Linking to https://github.com/ReactiveSocket/reactivesocket/issues/3 which shows some use cases where a message will have metadata. My goal is for a client to not need to do buffering and interpretation of previous frames in order to get this information. I prefer a little redundancy in the network protocol itself to enable simpler usage.

**Comment by benjchristensen** [comment] 2015-08-27 16:53
Resolved in #3

**Closed by benjchristensen** 2015-08-27 16:53 UTC
