### ISSUE TITLE
Extending HTTP/2 for ReactiveSocket

### ISSUE THREAD

**Issue by tmontgomery** [ReactiveSocket/reactivesocket#109] opened 2016-08-05 18:11 UTC
How can ReactiveSocket extend HTTP/2 for encapsulation?

**Comment by benjchristensen** [comment] 2016-08-30 20:55
Related: https://github.com/ReactiveSocket/reactivesocket/issues/84

**Comment by benjchristensen** [comment] 2016-10-19 21:05
Closing as duplicate of #84

**Closed by benjchristensen** 2016-10-19 21:05 UTC
